export const STAFF_CREATE_REQUEST = "STAFF_CREATE_REQUEST";
export const STAFF_CREATE_SUCCESS = "STAFF_CREATE_SUCCESS";
export const STAFF_CREATE_FAIL = "STAFF_CREATE_FAIL";

export const STAFF_DELETE_REQUEST = "STAFF_DELETE_REQUEST";
export const STAFF_DELETE_SUCCESS = "STAFF_DELETE_SUCCESS";
export const STAFF_DELETE_FAIL = "STAFF_DELETE_FAIL";

export const STAFF_UPDATE_REQUEST = "STAFF_UPDATE_REQUEST";
export const STAFF_UPDATE_SUCCESS = "STAFF_UPDATE_SUCCESS";
export const STAFF_UPDATE_FAIL = "STAFF_UPDATE_FAIL";
